"""Add import tracking fields to BookingForm

Revision ID: 4e726274f239
Revises: 60306aac34db
Create Date: 2025-05-31 10:28:35.999981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e726274f239'
down_revision = '60306aac34db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_source', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('import_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_form', schema=None) as batch_op:
        batch_op.drop_column('import_timestamp')
        batch_op.drop_column('import_source')

    # ### end Alembic commands ###
