"""Add source_identifier and is_active to CalendarSource

Revision ID: 60306aac34db
Revises: cf1ec034dc71
Create Date: 2025-05-31 09:11:39.508353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60306aac34db'
down_revision = 'cf1ec034dc71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_form', schema=None) as batch_op:
        batch_op.alter_column('is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('calendar_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_identifier', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_source', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('source_identifier')

    with op.batch_alter_table('booking_form', schema=None) as batch_op:
        batch_op.alter_column('is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
